rooms = ["AgACAgEAAxkBAAPaZG9BGoXNhKG0ugQX06RiSsLLi-UAAiatMRsQJXlHyXnccsN_amABAAMCAANzAAMvBA",
         "AgACAgEAAxkBAAPcZG9BHWBsVuMOVNDISKR44dvbTGkAAietMRsQJXlHQmk_ULE289oBAAMCAANzAAMvBA",
         "AgACAgEAAxkBAAPeZG9BIfSyqKvBdxCGjF3-PwtV-bgAAiitMRsQJXlHbUcotm9psy4BAAMCAANzAAMvBA",
         "AgACAgEAAxkBAAPgZG9BI_Px6DIYFoZ1ZS7LrRiRMoUAAimtMRsQJXlHeOdxh-zXw0UBAAMCAANzAAMvBA",
         "AgACAgEAAxkBAAPiZG9BJc0ZOfkvbbQsGZHf_ZdJwM8AAiqtMRsQJXlHIUdd6SiSUOsBAAMCAANzAAMvBA",
         "AgACAgEAAxkBAAPkZG9BJ2ZMx3ynLdv98SdNeZnQlSgAAiutMRsQJXlH4jmVsqB5_ocBAAMCAANzAAMvBA"]
hookah = "AgACAgEAAxkBAAICTWRwUKo218yGaecdB5fWeUFIo_ORAAJuqzEbECWBR5Ow5i-f4fYKAQADAgADcwADLwQ"

menu = {
    "drink": "AgACAgEAAxkBAAICg2RwVKFUA_yYuAM9UoApdsVg3v--AAJxqzEbECWBR9yq8FHimCkcAQADAgADcwADLwQ",
    "menu": "AgACAgEAAxkBAAIChWRwVKWyVe-4gk6MnJQKLinOgtykAAJyqzEbECWBR-1BpnzUpXHQAQADAgADcwADLwQ",
    "zakus": "AgACAgEAAxkBAAICh2RwVKhXkMBgtK6gJIJ5-j9aImsPAAJzqzEbECWBR2KSEAnhfNJYAQADAgADcwADLwQ",
    "salat": "AgACAgEAAxkBAAICiWRwVKvtxSt86lF-JrzpIqRq_WaEAAJ0qzEbECWBR3hyTiX65mFgAQADAgADcwADLwQ",
    "brekfast": "AgACAgEAAxkBAAICi2RwVK9eLwNg8-kg-EmRfbMjryhkAAJ1qzEbECWBR9kZvK8M03hUAQADAgADcwADLwQ",
    "hot": "AgACAgEAAxkBAAICjWRwVLKDE5INbFRS3zXbPzSQ9t_WAAJ2qzEbECWBR3h3ZPFYJhIHAQADAgADcwADLwQ",
    "burger": "AgACAgEAAxkBAAICj2RwVLQw4FCbxvcTMKFFvHRSYRlBAAJ3qzEbECWBR4S70erA8yRmAQADAgADcwADLwQ",
    "pizza": "AgACAgEAAxkBAAICkWRwVLhwUvfbbGBA-BPpvAduBdqfAAJ4qzEbECWBRzpbRAn4o8zxAQADAgADcwADLwQ"}
